name: Build Flasher Nusantara

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '.github/scripts/**'
      - 'daemon/**'
      - 'scripts/**'
      - 'profiler/**'
      - 'module/**'
      - 'preloader/**'
      - 'webui/**'
      - 'gamelist.txt'
      - 'version'

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build Flashable Zip
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.5.0
      with:
        ndk-version: r28b

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.0.2

    # Build Nusantara Daemon
    - name: Build Nusantara Daemon
      run: ndk-build \
        NDK_PROJECT_PATH=. \
        APP_BUILD_SCRIPT=daemon/Android.mk \
        NDK_APPLICATION_MK=daemon/Application.mk

    # Build Nusantara Profiler
    - name: Build Nusantara Profiler
      run: ndk-build \
        NDK_PROJECT_PATH=. \
        APP_BUILD_SCRIPT=profiler/Android.mk \
        NDK_APPLICATION_MK=profiler/Application.mk

    # Build WebUI
    - name: Build WebUI
      working-directory: ./webui
      run: |
        bun install
        bun run build
        cp -r ./dist/* ../module/webroot

    # Compile Flashable Zip
    - name: Compile Flashable Zip
      id: compileZip
      run: bash .github/scripts/compile_zip.sh

    # Upload Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: nusantara-build
        path: ${{ steps.compileZip.outputs.zipName }}

    # Upload To Telegram
    - name: Upload To Telegram
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        TITLE: Nusantara Tweaks
      run: |
        if [ -n "${{ secrets.CHAT_ID }}" ] && [ -n "${{ secrets.BOT_TOKEN }}" ]; then
          export VERSION=$(git rev-list --count HEAD)
          bash .github/scripts/telegram_bot.sh ${{ steps.compileZip.outputs.zipName }}
        else
          echo "Telegram bot token or chatid is undefined, please add it to repository secrets!"
          exit 1
        fi
        